version: '3'
services:
  tftp:
    image: "herrera/tftpd"
    network_mode: "host"
    ports:
      - "69:69/udp"
    volumes:
      - ../../../../out/tftp:/tftpboot
    privileged: true
  nfs:
    image: "erichough/nfs-server"
    network_mode: "host"
    ports:
      - "111:111"
      - "111:111/udp"
      - "2049:2049"
      - "2049:2049/udp"
      - "32765:32765"
      - "32765:32765/udp"
      - "32767:32767"
      - "32767:32767/udp"
    volumes:
      - ../../../../out/rootfs:/nfsshare
      - ./exports:/etc/exports:ro
    privileged: true
  bbb-devel:
    build: "./"
    volumes:
      - ../../../../:/aosp
      - ~/.ssh/:/home/aosp/.ssh/
      - ~/.gitconfig:/root/.gitconfig
    stdin_open: true
    tty: true

